# Generated by Django 5.0 on 2024-03-07 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_customuser_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
    ]
