# Generated by Django 5.0.3 on 2024-03-24 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_tasklabelmodel_task_labels'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_status',
            new_name='status',
        ),
    ]
